config/routes.rb
Rails.application.routes.draw do
  get 'goals/index'

  get 'goals/show'

  get 'goals/new'

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :goals
  root "sessions#new"
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :body, :user, :status, presence: true
  belongs_to :user
  validate :validate_completed

  after_initialize :default_completed

  def default_completed
    self.completed ||= false
  end

  def validate_completed
    if [true, false].include?(self.completed)
      true
    else
      self.errors.add(:completed, 'must be a boolean')
    end
  end

end

app/models/goal_comment.rb
class GoalComment < ActiveRecord::Base
  validates :author_id, :body, :goal_id, presence: true

  belongs_to :author
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id

  belongs_to :goal

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 3, allow_nil: true}
  has_many :goals

  after_initialize :ensure_session_token

  attr_reader :password

  def self.find_by_credentials(credentials)
    username = credentials[:username]
    password = credentials[:password]
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.password_digest = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

end

app/models/user_comment.rb
class UserComment < ActiveRecord::Base
  validates :body, :user_id, :author_id, presence: true

  belongs_to :user
  belongs_to :author,
    class_name: "User",
    foreign_key: :author_id,
    primary_key: :id


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :signed_in?, :current_user

  def current_user
    return nil if session[:token].nil?
    @current_user ||= User.find_by(session_token: session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    session[:token] = user.reset_session_token!
  end

  def sign_out
    current_user.reset_session_token!
    session[:token] = nil
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    #all public goals
  end

  def show
    #all user's goals
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :show
    end
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      redirect_to goal_url(@goal)
    else
      @errors = @goal.errors.full_messages
      render :new
    end
  end

  def destroy
    @goal = Goal.destroy(params[:id])
    redirect_to user_url(@goal.user)
  end

  private

  def goal_params
    params.require(:goal).permit(:body, :status, :completed)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(user_params)
    if @user.nil?
      @user = User.new
      render :new
    else
      sign_in(@user)
      redirect_to users_url
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to users_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
def send_auth_token
  <<-HTML.html_safe
    <input type="hidden" name="authenticity_token" value="#{form_authenticity_token}">
  HTML
end

end

app/helpers/goals_helper.rb
module GoalsHelper
  def all_public_goals
    Goal.where(status: "Public")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<h1>All Public Goals</h1>

<ul>
  <% all_public_goals.each do |goal| %>
    <li><%= goal.body %>. Goal completed: <%= goal.completed %>. by: <%= goal.user.username %></li>
  <% end %>
</ul>

<%= link_to "Create Goal", new_goal_url %>

app/views/goals/new.html.erb
<h1>Create Goal</h1>
<% if !@errors.nil? %>
  <% @errors.each do |error| %>
    <%= error %>
  <% end %>
<% end %>
<form action="<%= goals_url %>" method="post">
  <%= send_auth_token %>

  <label>Body
    <input type="string" name="goal[body]" value="<%= @goal.body %>">
  </label>

  <label>Status:

    <label>Private
      <input
        type="radio"
        name="goal[status]"
        value="Private"
        <%= "checked" if @goal.status == "private" %> >
    </label>

    <label>Public
      <input
        type="radio"
        name="goal[status]"
        value="Public"
        <%= "checked" if @goal.status == "Public" %> >
    </label>

  </label>

  <button>Submit Goal</button>

</form>

app/views/goals/show.html.erb
<h1><%= @goal.body %></h1>



<form action="<%= goal_url(@goal) %>" method="post">
  <%= send_auth_token %>
  <input type="hidden" name="_method" value="patch">

  <label>Goal Body
    <input type="string" name="goal[body]" value="<%= @goal.body %>">
  </label>

  <label>
    Status
    <label>Private
      <input type="radio"
      name="goal[status]"
      value="Private"
      <%= "checked" if @goal.status == "Private" %>
      >
    </label>

    <label>Public
      <input type="radio"
      name="goal[status]"
      value="Public"
      <%= "checked" if @goal.status == "Public" %>
      >
    </label>
  </label>

  <br>
  Task completed - <%= @goal.completed %>
  <br>

  <button>Submit</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user.nil? %>
  <%= link_to 'Sign Up', new_user_url %> |
  <%= link_to 'Sign In', new_session_url %>
<% else %>
  Welcome, <%= current_user.username %> |
  <%= link_to 'Sign Out', session_url, method: 'delete' %>
<% end %>

<% unless flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <%= send_auth_token %>
  <label>Username
    <input type="string" name="user[username]" value="<%= @user.username %>">
  </label>
  <label>Password
    <input type="string" name="user[password]" value="<%= @user.password %>">
  </label>
  <button>Sign Up</button>
</form>

app/views/users/show.html.erb
<h1> <%= current_user.username %> </h1>
<h2>To Do List: </h2>

<ul>
<% current_user.goals.each do |goal| %>
  <li>
    <%= link_to goal.body, goal_url(goal) %> | <%= goal.status %> | <%= goal.completed %>
    <form action="<%= goal_url(goal) %>" method="post">
      <%= send_auth_token %>
      <input type="hidden" name="_method" value="patch">
      <input type="hidden" name="goal[completed]" value="true">
      <button>Completed</button>
    </form>
    <%= button_to "Destroy Task", goal_url(goal), method: "delete" %>
  </li>
  <% end %>
</ul>